# Example Steam Workshop mod configuration
# This is a real CK3 mod from Steam Workshop for testing
[upstream]
workshop = "2218107383"  # "More Decisions" mod - popular and actively maintained CK3 mod
localization = ["localization/english"]
language = "english"