name: Stellaris translate

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - "stellaris/**/upstream/localisation/**"
      - "stellaris/**/upstream/**/localisation/**"

jobs:
  translate:
    runs-on: self-hosted
    permissions:
      contents: write
    env:
      GOOGLE_AI_STUDIO_TOKEN: "${{secrets.GOOGLE_AI_STUDIO_TOKEN}}"
    steps:
      - uses: actions/checkout@v5
        with:
          submodules: true
      - uses: actions/cache@v4
        with:
          key: translate-cache
          path: "**.db"
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v5
        with:
          cache: 'pnpm'
          node-version-file: .node-version
      - run: pnpm install --frozen-lockfile
      - run: pnpm stellaris
      - uses: stefanzweifel/git-auto-commit-action@v6
        with:
          push: true
          commit: --signoff
          default_author: github_actor
          commit_message: "chore(stellaris): 번역 파일 업데이트 [skip ci]"
