name: CK3 translate

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - "ck3/**/upstream"
      - "ck3/**/upstream/localization/**"
      - "ck3/**/upstream/**/localisation/**"

jobs:
  translate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      GOOGLE_AI_STUDIO_TOKEN: "${{secrets.GOOGLE_AI_STUDIO_TOKEN}}"
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: actions/cache@v4
        with:
          key: translate-cache
          path: "**.db"
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          cache: 'pnpm'
          node-version-file: .node-version
      - run: pnpm install --frozen-lockfile
      - run: pnpm ck3
      - uses: stefanzweifel/git-auto-commit-action@v6
        with:
          push: true
          commit: --signoff
          default_author: github_actor
          commit_message: "chore: 업스트림 저장소 업데이트"
