name: Update upstream

on:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *" # 매시간마다 작동

jobs:
  update-upstream:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: 소스코드 체크아웃
        uses: actions/checkout@v5
      - name: pnpm 설정
        uses: pnpm/action-setup@v4
      - name: Node.js 설정
        uses: actions/setup-node@v4
        with:
          cache: 'pnpm'
          node-version-file: .node-version
      - name: 의존성 설치
        run: pnpm install --frozen-lockfile
      - name: 업스트림 저장소 업데이트
        run: pnpm upstream
      - name: 변경사항 업데이트
        uses: stefanzweifel/git-auto-commit-action@v6
        with:
          commit_message: "chore: 업스트림 저장소 업데이트"
